package blog.modelo;

// Generated Oct 24, 2014 1:54:18 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BlogTag generated by hbm2java
 */
@Entity
@Table(name = "blog_tag")
public class BlogTag implements java.io.Serializable {

	private Integer id;
	private BlogPost blogPost;
	private String tag;
	private String tagClean;

	public BlogTag() {
	}

	public BlogTag(BlogPost blogPost, String tag, String tagClean) {
		this.blogPost = blogPost;
		this.tag = tag;
		this.tagClean = tagClean;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "post_id", nullable = false)
	public BlogPost getBlogPost() {
		return this.blogPost;
	}

	public void setBlogPost(BlogPost blogPost) {
		this.blogPost = blogPost;
	}

	@Column(name = "tag", nullable = false, length = 45)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "tag_clean", nullable = false, length = 45)
	public String getTagClean() {
		return this.tagClean;
	}

	public void setTagClean(String tagClean) {
		this.tagClean = tagClean;
	}

}
